# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 220b6bc0fcb97475cbe3595c71b6e30825f3b1b5647df0d0d02a19bfee4082e313c3eb8dc2b236450d096a6346ed45bb304ffd168b8c4377ed34a8f2fabfb6dc

test:
  secret_key_base: 528d494999319094425c28226d37168aaf0319bfc9b7426c1cf3249680f8c2da253576925ff953b2c5ad433a04db9ee83644a08f76c1476ca352cd10ce024f31

production: &production
  <% if ((false == Rails.env.test?) && (false == Rails.env.development?)) %>
  secret_key_base: <%= File.read(File.join(Rails.application.config.root, "config", "secret.token")) %>
  <% end %>
